### ISSUE TITLE
UnionFindPartition.remove, .split not working as intended

### ISSUE THREAD

**Issue by markalavin** [gstamatelat/partition#2]
I am using UnionFindPartition< Integer > to compute the size of connected components as elements are removed, using either the `remove` or the `split` methods.   There are three Items -- 1, 2, and 3 -- and initially joined using `union(1,2)` and `union(1,3)` to produce
`{1=Item { item=1, parent=1 }, 2=Item { item=2, parent=1 }, 3=Item { item=3, parent=1 }}`.   In the next step, I call `remove(1)`, which should break the remaining elements into two singleton components, if I understand correctly.   However, when I look at the partition after the call, I see
`{2=Item { item=2, parent=3 }, 3=Item { item=3, parent=3 }}`, which seems to say that items 2 and 3 still belong to the same connected component in spite of the fact that we have removed the "bridge" element (1).

Am I misunderstanding the intent of the code?   Am I using the methods incorrectly?   Or is there a bug?

**Comment by gstamatelat** [comment]
@markalavin This is the intended behavior.

The `remove` method will completely remove an element from the partition (if it is present) but it will keep the rest of the elements inside their original components. Hopefully, I can make this behavior more clear in the docs. Likewise, the `split` method will move the element into its own singleton component.

This happens because, when adding an element, union-find (and the partition interface in general) does not keep history of the element via which it was approached. Basically, when connecting `x` with `y` with the call `union(x, y)`, the partition doesn't understand that `x` is connected to `y` but rather that `x` and `y` are now in the same component.

That said, a graph data structure is more suitable to your problem. A graph, unlike union-find, understands edges and it is possible to use BFS/DFS (assuming undirected) to determine the connected components and find their size. These algorithms are typically not as efficient as union-find operations.

**Comment by markalavin** [comment]
Giorgios, thanks! for the quick response.   Googling further, I think what I'm looking for is "fully dynamic connectivy", as implement in C++ in https://github.com/16lawrencel/dynamic-graphs and in JavaScript in https://github.com/mikolalysenko/dynamic-forest; alas, no ready-to-use Java implementation...
